const wordLibrary = {
    articles: ["a", "an", "the"],
    pronouns: {
        singular: ["he", "she", "it"],
        plural: ["they", "we"],
        firstPerson: ["i"],
        secondPerson: ["you"]
    },
    rules: {
        vowels: ["a", "e", "i", "o", "u"]
    },
    nouns: {
        cow: ["cow", "cows"],
        boy: ["boy", "boys"],
        apple: ["apple", "apples"],
        girl: ["girl", "girls"],
        car: ["car", "cars"],
        child: ["child", "children"],
        mouse: ["mouse", "mice"],
        book: ["book", "books"],
        party: ["party", "parties"],
        tree: ["tree", "trees"],
        computer: ["computer", "computers"],
        phone: ["phone", "phones"],
        house: ["house", "houses"],
        city: ["city", "cities"],
        country: ["country", "countries"],
        friend: ["friend", "friends"],
        dog: ["dog", "dogs"],
        cat: ["cat", "cats"],
        person: ["person", "people"],
        man: ["man", "men"],
        woman: ["woman", "women"],
        foot: ["foot", "feet"],
        tooth: ["tooth", "teeth"],
        goose: ["goose", "geese"],
        sheep: ["sheep", "sheep"],
        fish: ["fish", "fish"],
        deer: ["deer", "deer"]
    },
    verbs: {
        eat: { base: "eat", present: "eats", past: "ate", pastParticiple: "eaten", ing: "eating" },
        go: { base: "go", present: "goes", past: "went", pastParticiple: "gone", ing: "going" },
        goes: { base: "go" },
        went: { base: "go" },
        buy: { base: "buy", present: "buys", past: "bought", pastParticiple: "bought", ing: "buying" },
        play: { base: "play", present: "plays", past: "played", pastParticiple: "played", ing: "playing" },
        see: { base: "see", present: "sees", past: "saw", pastParticiple: "seen", ing: "seeing" },
        talk: { base: "talk", present: "talks", past: "talked", pastParticiple: "talked", ing: "talking" },
        walk: { base: "walk", present: "walks", past: "walked", pastParticiple: "walked", ing: "walking" },
        run: { base: "run", present: "runs", past: "ran", pastParticiple: "run", ing: "running" },
        write: { base: "write", present: "writes", past: "wrote", pastParticiple: "written", ing: "writing" },
        speak: { base: "speak", present: "speaks", past: "spoke", pastParticiple: "spoken", ing: "speaking" },
        
        // Extended verb list for better grammar checking
        abide: { base: "abide", present: "abides", past: "abode", pastParticiple: "abode", ing: "abiding" },
        accept: { base: "accept", present: "accepts", past: "accepted", pastParticiple: "accepted", ing: "accepting" },
        achieve: { base: "achieve", present: "achieves", past: "achieved", pastParticiple: "achieved", ing: "achieving" },
        act: { base: "act", present: "acts", past: "acted", pastParticiple: "acted", ing: "acting" },
        add: { base: "add", present: "adds", past: "added", pastParticiple: "added", ing: "adding" },
        answer: { base: "answer", present: "answers", past: "answered", pastParticiple: "answered", ing: "answering" },
        appear: { base: "appear", present: "appears", past: "appeared", pastParticiple: "appeared", ing: "appearing" },
        arise: { base: "arise", present: "arises", past: "arose", pastParticiple: "arisen", ing: "arising" },
        ask: { base: "ask", present: "asks", past: "asked", pastParticiple: "asked", ing: "asking" },
        awake: { base: "awake", present: "awakes", past: "awoke", pastParticiple: "awoken", ing: "awaking" },
        be: { base: "be", present: "is", past: "was", pastParticiple: "been", ing: "being" },
        bear: { base: "bear", present: "bears", past: "bore", pastParticiple: "born", ing: "bearing" },
        beat: { base: "beat", present: "beats", past: "beat", pastParticiple: "beaten", ing: "beating" },
        become: { base: "become", present: "becomes", past: "became", pastParticiple: "become", ing: "becoming" },
        begin: { base: "begin", present: "begins", past: "began", pastParticiple: "begun", ing: "beginning" },
        believe: { base: "believe", present: "believes", past: "believed", pastParticiple: "believed", ing: "believing" },
        bite: { base: "bite", present: "bites", past: "bit", pastParticiple: "bitten", ing: "biting" },
        bleed: { base: "bleed", present: "bleeds", past: "bled", pastParticiple: "bled", ing: "bleeding" },
        blow: { base: "blow", present: "blows", past: "blew", pastParticiple: "blown", ing: "blowing" },
        break: { base: "break", present: "breaks", past: "broke", pastParticiple: "broken", ing: "breaking" },
        bring: { base: "bring", present: "brings", past: "brought", pastParticiple: "brought", ing: "bringing" },
        build: { base: "build", present: "builds", past: "built", pastParticiple: "built", ing: "building" },
        burn: { base: "burn", present: "burns", past: "burnt", pastParticiple: "burnt", ing: "burning" },
        call: { base: "call", present: "calls", past: "called", pastParticiple: "called", ing: "calling" },
        carry: { base: "carry", present: "carries", past: "carried", pastParticiple: "carried", ing: "carrying" },
        catch: { base: "catch", present: "catches", past: "caught", pastParticiple: "caught", ing: "catching" },
        choose: { base: "choose", present: "chooses", past: "chose", pastParticiple: "chosen", ing: "choosing" },
        come: { base: "come", present: "comes", past: "came", pastParticiple: "come", ing: "coming" },
        cost: { base: "cost", present: "costs", past: "cost", pastParticiple: "cost", ing: "costing" },
        cut: { base: "cut", present: "cuts", past: "cut", pastParticiple: "cut", ing: "cutting" },
        do: { base: "do", present: "does", past: "did", pastParticiple: "done", ing: "doing" },
        draw: { base: "draw", present: "draws", past: "drew", pastParticiple: "drawn", ing: "drawing" },
        dream: { base: "dream", present: "dreams", past: "dreamt", pastParticiple: "dreamt", ing: "dreaming" },
        drink: { base: "drink", present: "drinks", past: "drank", pastParticiple: "drunk", ing: "drinking" },
        drive: { base: "drive", present: "drives", past: "drove", pastParticiple: "driven", ing: "driving" },
        fall: { base: "fall", present: "falls", past: "fell", pastParticiple: "fallen", ing: "falling" },
        feed: { base: "feed", present: "feeds", past: "fed", pastParticiple: "fed", ing: "feeding" },
        feel: { base: "feel", present: "feels", past: "felt", pastParticiple: "felt", ing: "feeling" },
        fight: { base: "fight", present: "fights", past: "fought", pastParticiple: "fought", ing: "fighting" },
        find: { base: "find", present: "finds", past: "found", pastParticiple: "found", ing: "finding" },
        fly: { base: "fly", present: "flies", past: "flew", pastParticiple: "flown", ing: "flying" },
        forget: { base: "forget", present: "forgets", past: "forgot", pastParticiple: "forgotten", ing: "forgetting" },
        forgive: { base: "forgive", present: "forgives", past: "forgave", pastParticiple: "forgiven", ing: "forgiving" },
        freeze: { base: "freeze", present: "freezes", past: "froze", pastParticiple: "frozen", ing: "freezing" },
        get: { base: "get", present: "gets", past: "got", pastParticiple: "got", ing: "getting" },
        give: { base: "give", present: "gives", past: "gave", pastParticiple: "given", ing: "giving" },
        grow: { base: "grow", present: "grows", past: "grew", pastParticiple: "grown", ing: "growing" },
        have: { base: "have", present: "has", past: "had", pastParticiple: "had", ing: "having" },
        hear: { base: "hear", present: "hears", past: "heard", pastParticiple: "heard", ing: "hearing" },
        hide: { base: "hide", present: "hides", past: "hid", pastParticiple: "hidden", ing: "hiding" },
        hit: { base: "hit", present: "hits", past: "hit", pastParticiple: "hit", ing: "hitting" },
        hold: { base: "hold", present: "holds", past: "held", pastParticiple: "held", ing: "holding" },
        hurt: { base: "hurt", present: "hurts", past: "hurt", pastParticiple: "hurt", ing: "hurting" },
        keep: { base: "keep", present: "keeps", past: "kept", pastParticiple: "kept", ing: "keeping" },
        know: { base: "know", present: "knows", past: "knew", pastParticiple: "known", ing: "knowing" },
        lay: { base: "lay", present: "lays", past: "laid", pastParticiple: "laid", ing: "laying" },
        lead: { base: "lead", present: "leads", past: "led", pastParticiple: "led", ing: "leading" },
        learn: { base: "learn", present: "learns", past: "learnt", pastParticiple: "learnt", ing: "learning" },
        leave: { base: "leave", present: "leaves", past: "left", pastParticiple: "left", ing: "leaving" },
        lend: { base: "lend", present: "lends", past: "lent", pastParticiple: "lent", ing: "lending" },
        let: { base: "let", present: "lets", past: "let", pastParticiple: "let", ing: "letting" },
        lie: { base: "lie", present: "lies", past: "lay", pastParticiple: "lain", ing: "lying" },
        lose: { base: "lose", present: "loses", past: "lost", pastParticiple: "lost", ing: "losing" },
        make: { base: "make", present: "makes", past: "made", pastParticiple: "made", ing: "making" },
        mean: { base: "mean", present: "means", past: "meant", pastParticiple: "meant", ing: "meaning" },
        meet: { base: "meet", present: "meets", past: "met", pastParticiple: "met", ing: "meeting" },
        pay: { base: "pay", present: "pays", past: "paid", pastParticiple: "paid", ing: "paying" },
        put: { base: "put", present: "puts", past: "put", pastParticiple: "put", ing: "putting" },
        read: { base: "read", present: "reads", past: "read", pastParticiple: "read", ing: "reading" },
        ride: { base: "ride", present: "rides", past: "rode", pastParticiple: "ridden", ing: "riding" },
        ring: { base: "ring", present: "rings", past: "rang", pastParticiple: "rung", ing: "ringing" },
        rise: { base: "rise", present: "rises", past: "rose", pastParticiple: "risen", ing: "rising" },
        say: { base: "say", present: "says", past: "said", pastParticiple: "said", ing: "saying" },
        send: { base: "send", present: "sends", past: "sent", pastParticiple: "sent", ing: "sending" },
        set: { base: "set", present: "sets", past: "set", pastParticiple: "set", ing: "setting" },
        sew: { base: "sew", present: "sews", past: "sewed", pastParticiple: "sewn", ing: "sewing" },
        shake: { base: "shake", present: "shakes", past: "shook", pastParticiple: "shaken", ing: "shaking" },
        shine: { base: "shine", present: "shines", past: "shone", pastParticiple: "shone", ing: "shining" },
        shoot: { base: "shoot", present: "shoots", past: "shot", pastParticiple: "shot", ing: "shooting" },
        show: { base: "show", present: "shows", past: "showed", pastParticiple: "shown", ing: "showing" },
        sing: { base: "sing", present: "sings", past: "sang", pastParticiple: "sung", ing: "singing" },
        sink: { base: "sink", present: "sinks", past: "sank", pastParticiple: "sunk", ing: "sinking" },
        sit: { base: "sit", present: "sits", past: "sat", pastParticiple: "sat", ing: "sitting" },
        sleep: { base: "sleep", present: "sleeps", past: "slept", pastParticiple: "slept", ing: "sleeping" },
        slide: { base: "slide", present: "slides", past: "slid", pastParticiple: "slid", ing: "sliding" },
        smell: { base: "smell", present: "smells", past: "smelt", pastParticiple: "smelt", ing: "smelling" },
        spend: { base: "spend", present: "spends", past: "spent", pastParticiple: "spent", ing: "spending" },
        stand: { base: "stand", present: "stands", past: "stood", pastParticiple: "stood", ing: "standing" },
        steal: { base: "steal", present: "steals", past: "stole", pastParticiple: "stolen", ing: "stealing" },
        stick: { base: "stick", present: "sticks", past: "stuck", pastParticiple: "stuck", ing: "sticking" },
        sting: { base: "sting", present: "stings", past: "stung", pastParticiple: "stung", ing: "stinging" },
        swim: { base: "swim", present: "swims", past: "swam", pastParticiple: "swum", ing: "swimming" },
        take: { base: "take", present: "takes", past: "took", pastParticiple: "taken", ing: "taking" },
        teach: { base: "teach", present: "teaches", past: "taught", pastParticiple: "taught", ing: "teaching" },
        tear: { base: "tear", present: "tears", past: "tore", pastParticiple: "torn", ing: "tearing" },
        tell: { base: "tell", present: "tells", past: "told", pastParticiple: "told", ing: "telling" },
        think: { base: "think", present: "thinks", past: "thought", pastParticiple: "thought", ing: "thinking" },
        throw: { base: "throw", present: "throws", past: "threw", pastParticiple: "thrown", ing: "throwing" },
        understand: { base: "understand", present: "understands", past: "understood", pastParticiple: "understood", ing: "understanding" },
        wake: { base: "wake", present: "wakes", past: "woke", pastParticiple: "woken", ing: "waking" },
        wear: { base: "wear", present: "wears", past: "wore", pastParticiple: "worn", ing: "wearing" },
        win: { base: "win", present: "wins", past: "won", pastParticiple: "won", ing: "winning" },
        write: { base: "write", present: "writes", past: "wrote", pastParticiple: "written", ing: "writing" }
    },
    adjectives: {
        good: ["good", "better", "best"],
        bad: ["bad", "worse", "worst"],
        big: ["big", "bigger", "biggest"],
        small: ["small", "smaller", "smallest"],
        tall: ["tall", "taller", "tallest"],
        short: ["short", "shorter", "shortest"],
        fast: ["fast", "faster", "fastest"],
        slow: ["slow", "slower", "slowest"],
        happy: ["happy", "happier", "happiest"],
        sad: ["sad", "sadder", "saddest"],
        beautiful: ["beautiful", "more beautiful", "most beautiful"],
        intelligent: ["intelligent", "more intelligent", "most intelligent"],
        important: ["important", "more important", "most important"],
        interesting: ["interesting", "more interesting", "most interesting"],
        difficult: ["difficult", "more difficult", "most difficult"],
        easy: ["easy", "easier", "easiest"],
        hot: ["hot", "hotter", "hottest"],
        cold: ["cold", "colder", "coldest"],
        old: ["old", "older", "oldest"],
        young: ["young", "younger", "youngest"],
        new: ["new", "newer", "newest"],
        clean: ["clean", "cleaner", "cleanest"],
        dirty: ["dirty", "dirtier", "dirtiest"]
    },
    // Common words for spell checking
    commonWords: [
        "the", "be", "to", "of", "and", "a", "in", "that", "have", "i", "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
        "this", "but", "his", "by", "from", "they", "she", "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
        "so", "up", "out", "if", "about", "who", "get", "which", "go", "me", "when", "make", "can", "like", "time", "no", "just",
        "him", "know", "take", "people", "into", "year", "your", "good", "some", "could", "them", "see", "other", "than", "then",
        "now", "look", "only", "come", "its", "over", "think", "also", "back", "after", "use", "two", "how", "our", "work", "first",
        "well", "way", "even", "new", "want", "because", "any", "these", "give", "day", "most", "us", "is", "was", "are", "been",
        "has", "had", "were", "said", "each", "which", "their", "time", "will", "about", "if", "up", "out", "many", "then", "them",
        "can", "said", "each", "which", "she", "do", "how", "their", "if", "will", "up", "other", "about", "out", "many", "then",
        "them", "these", "so", "some", "her", "would", "make", "like", "into", "him", "has", "two", "more", "very", "what", "know",
        "just", "first", "get", "over", "think", "where", "much", "go", "well", "were", "been", "through", "when", "much", "before",
        "here", "why", "how", "should", "because"
    ],
    // Prepositions for grammar checking
    prepositions: [
        "at", "in", "on", "by", "for", "with", "about", "against", "between", "into", "through", "during", "before", "after",
        "above", "below", "to", "from", "up", "down", "out", "off", "over", "under", "again", "further", "then", "once"
    ],
    // Conjunctions
    conjunctions: [
        "and", "but", "or", "nor", "for", "yet", "so", "although", "because", "since", "unless", "while", "whereas", "if", "even"
    ],
    // Time indicators for tense correction
    timeIndicators: {
        past: ["yesterday", "last", "ago", "previously", "earlier", "before", "then", "once", "former"],
        present: ["today", "now", "currently", "presently", "at present", "right now", "these days"],
        future: ["tomorrow", "next", "soon", "later", "eventually", "in future", "will", "shall", "going to"]
    }
};
